title: teknolojitasarimci
email: murseleren@hotmail.com.tr
description: "Teknoloji, Tasarım, İnovasyon, Zeka Oyunları, Rehberlik ve Kişisel Gelişim"
url: "https://teknolojitasarimci.github.io"
permalink: /:year/:month/:day/:title/

# Gelecek tarihli veya zaman dilimi farkı olan yazıları gizlememesi için:
future: true

plugins:
  - jekyll-seo-tag
